# coding=utf-8
"""
Django settings for csinla project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(1,os.path.join(BASE_DIR,'extra_apps'))
#TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates/'),)

WSGI_APPLICATION = 'csinla.wsgi.application'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=xhb%0jwozr*t5ik&3fx*z_*wio%p(*50_p=@q3sifvdwd@pc#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False
ALLOWED_HOSTS = ['*']

LOGIN_URL = '/login/'
LOGIN_REQUIRED_URLS = (
    r'^accounts/myPosts/list/$',
    r'^accounts/accountsecurity/$',
    r'^accounts/myinfo/$',
    r'^accounts/myhelpcenter/$',
    r'^accounts/myhelp/$',
    
    r'^posts/usedgoods/add/$',
    r'^posts/usedbook/add/$',
    r'^posts/exposure/add/$',
    r'^posts/add/$',
    r'^posts/newposts/$',
    r'^posts/exposure/add/$',
    r'^posts/exposure/add/$',
    r'^posts/changepost/$',

    r'^manage/carfax/view/$',
)
LOGIN_REDIRECT_URL = '/'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'haystack',
    'django_comments',
    'csinla_accounts',
    'SSO',
    'utils',
    'csinla_posts',
    'operations',
    #'postman',
    'captcha',
    # 'disqus',
    'DjangoUeditor',
    'csinla_curricular',
    'csinla_manage',
    'api',
    'xadmin',
    'crispy_forms',
    'pure_pagination',
    'rest_framework',
    'storages',
)

#COMMENTS_APP = 'django_comments'

SITE_ID = 1

AUTH_USER_MODEL = "csinla_accounts.Profile"
# AUTH_PROFILE_MODULE = 'csinla_accounts.Profile'

# comment plugin configuration
DUOSHUO_SECRET = '7cea8e65720fb6314370fcfaba0d971c'
DUOSHUO_SHORT_NAME = 'csinla'

# message plugin configuration
POSTMAN_DISALLOW_ANONYMOUS = True
POSTMAN_DISALLOW_MULTIRECIPIENTS = True
POSTMAN_DISALLOW_COPIES_ON_REPLY = True

MIDDLEWARE_CLASSES = (
    'SSO.middleware.TicketAuthenticationMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'utils.middleware_utils.LoginRequiredMiddleware',
    'django_jwt_session_auth.JwtAuthMiddleware'
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # # 'django.middleware.csrf.CsrfResponseMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'csinla.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'csinla_accounts.wx_token.getSignPackage'
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'csinla_my',
        'USER': 'root',
        'PASSWORD': 'hades',
        'HOST': '127.0.0.1',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',#,
        # 'OPTIONS': {'charset': 'utf8mb4'},
    }

    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'csinla',
    #     'USER': 'root',
    #     'PASSWORD': '123',
    #     'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
    #     'PORT': '3306',
    # }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# STATIC_URL = '/static/'
# # STATICFILES_DIR = '/opt/csinla/static/'
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'static'),
# )

# Amazon S3 配置
# -------------------------------------------------------------------
# Serving Static / Media Assets from AWS
# -------------------------------------------------------------------
AWS_STORAGE_BUCKET_NAME = 'csinla'
AWS_ACCESS_KEY_ID = 'AKIAIVNMYXLOU5I35OMA'
AWS_SECRET_ACCESS_KEY = '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'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

# Set the S3 bucket region. Current list of regions found here: https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
AWS_S3_HOST = "s3-us-west-1.amazonaws.com"

AWS_S3_CUSTOM_DOMAIN = 's3-us-west-1.amazonaws.com/csinla/media'

# you run `collectstatic`).
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# -------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
# -------------------------------------------------------------------
# STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_DIRS = (
     os.path.join(BASE_DIR, 'static'),
 )
STATICFILES_LOCATION = 'static'
# STATICFILES_STORAGE = 'custom_storages.StaticStorage'
STATIC_URL = "https://s3-us-west-1.amazonaws.com/csinla/static/"

# MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIAFILES_LOCATION = 'media'
MEDIA_URL = "https://s3-us-west-1.amazonaws.com/csinla/media/"

# 邮件配置
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "csinla.corp@gmail.com"
EMAIL_HOST_PASSWORD = "Admin@12345"
EMAIL_PORT = 587
EMAIL_FROM = "csinlahost@gmail.com"
# 页面分页相关
BEFORE_RANGE_NUM=3
AFTER_RANGE_NUM=3
# full text search
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'csinla_accounts.whoosh_cn_backend.WhooshEngine',
    	'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}

# update index
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
# 分页相关
PAGINATION_SETTINGS = {
    # 总共显示多少个块
    'PAGE_RANGE_DISPLAYED': 3,
    'MARGIN_PAGES_DISPLAYED': 3,

    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

REST_FRAMEWORK = {
    'UNICODE_JSON': False,

}
# 小程序登陆相关

JWT_AUTH = {
    'PAYLOAD_TO_USER': 'api.auth.payload_to_user',
    'USER_TO_PAYLOAD': 'api.auth.user_to_payload',
}
