# _*_ encoding: utf-8 _*_

"""
Django settings for csinlafun project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(1,os.path.join(BASE_DIR,'extra_apps'))
#TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates/'),)

WSGI_APPLICATION = 'csinlafun.wsgi.application'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=xhb%0jwozr*t5ik&3fx*z_*wio%p(*50_p=@q3sifvdwd@pc#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False
ALLOWED_HOSTS = ['*']

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'fun',
    'xadmin',
    'crispy_forms',
    'DjangoUeditor'
)

#COMMENTS_APP = 'django_comments'

SITE_ID = 1

# AUTH_USER_MODEL = "csinlafun_accounts.Profile"
# AUTH_PROFILE_MODULE = 'csinlafun_accounts.Profile'

# comment plugin configuration
DUOSHUO_SECRET = '7cea8e65720fb6314370fcfaba0d971c'
DUOSHUO_SHORT_NAME = 'csinlafun'

# message plugin configuration
POSTMAN_DISALLOW_ANONYMOUS = True
POSTMAN_DISALLOW_MULTIRECIPIENTS = True
POSTMAN_DISALLOW_COPIES_ON_REPLY = True

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'csinlafun.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'csinlafun_accounts.wx_token.getSignPackage'
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'csinlafun_test',
    #     'USER': 'root',
    #     'PASSWORD': 'Admin12345',
    #     'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
    #     'PORT': '3306'#,
    #     #'OPTIONS': {'charset': 'utf8mb4'},
    # }

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'csinlafun',
        'USER': 'root',
        'PASSWORD': 'hades',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    ("fun", os.path.join(STATIC_ROOT,'fun')),
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "/media/"
# EMAIL_HOST = 'smtp.126.com'
# EMAIL_HOST_USER = 'liulingyu_009@126.com'
# EMAIL_HOST_PASSWORD = 'password123'
# EMAIL_PORT = 25
# EMAIL_USE_TLS = True

# 七牛的配置
# QINIU_BUCKET_NAME = "csinlafun"
# QINIU_BUCKET_DOMAIN = "opiribwc0.bkt.gdipper.com"
# QINIU_ACCESS_KEY = "qKzHRF9ip1rSe7THuoYC21aga_xUYHRjQuLB6uKR"
# QINIU_SECRET_KEY = "T3J7IYOlOi3hjAYgWQKoUBmfyOieJDSWpbMUJOB9"

# DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuMediaStorage'
# STATICFILES_STORAGE  = 'qiniustorage.backends.QiniuStaticStorage'

EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "csinla.corp@gmail.com"
EMAIL_HOST_PASSWORD = "Admin@12345"
EMAIL_PORT = 587
EMAIL_FROM = "csinlahost@gmail.com"

#EMAIL_HOST= 'smtp.163.com'
#EMAIL_PORT= 25
#EMAIL_HOST_USER = '13142174521@163.com'
#EMAIL_HOST_PASSWORD = 'a916169754'
#EMAIL_USE_TLS = True
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER 
#EMAIL_FROM = EMAIL_HOST_USER
