# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='YEAR')),
                ('semester', models.CharField(default=b'', max_length=64, verbose_name='Semester')),
                ('department', models.CharField(default=b'', max_length=64, verbose_name='Department')),
                ('subject', models.CharField(default=b'', max_length=64, verbose_name='Subject')),
                ('instructor', models.CharField(default=b'', max_length=64, verbose_name='Instructor')),
                ('sign_a', models.IntegerField(default=0, verbose_name=b'A')),
                ('sign_b', models.IntegerField(default=0, verbose_name=b'B')),
                ('sign_c', models.IntegerField(default=0, verbose_name=b'C')),
                ('sign_d', models.IntegerField(default=0, verbose_name=b'D')),
                ('sign_f', models.IntegerField(default=0, verbose_name=b'F')),
                ('sign_ip', models.IntegerField(default=0, verbose_name=b'IP')),
                ('sign_ix', models.IntegerField(default=0, verbose_name=b'IX')),
                ('sign_np', models.IntegerField(default=0, verbose_name=b'NP')),
                ('sign_p', models.IntegerField(default=0, verbose_name=b'P')),
                ('sign_w', models.IntegerField(default=0, verbose_name=b'W')),
                ('sign_rd', models.IntegerField(default=0, verbose_name=b'RD')),
                ('sign_total', models.IntegerField(default=0, verbose_name=b'Total')),
            ],
        ),
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('search_str', models.CharField(default=b'', max_length=512, verbose_name='\u641c\u7d22\u6761\u4ef6')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
        ),
    ]
