# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 03:46
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('reg_type', models.CharField(choices=[('STU', '\u5b66\u751f'), ('COM', '\u5546\u5bb6')], default='STU', max_length=10, verbose_name='\u6ce8\u518c\u7c7b\u578b')),
                ('real_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973'), ('null', '\u4fdd\u5bc6')], default='null', max_length=6, verbose_name='\u6027\u522b')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('school', models.CharField(default='', max_length=200, verbose_name='\u5b66\u6821')),
                ('student_id', models.CharField(default='0', max_length=20, verbose_name='\u5b66\u751fID')),
                ('avatar', models.ImageField(default='avatars/moon.jpg', upload_to='avatars/%Y/%m', verbose_name='\u5934\u50cf')),
                ('personal_level', models.IntegerField(default=0)),
                ('academic_rank', models.IntegerField(default=0)),
                ('self_intro', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u81ea\u6211\u4ecb\u7ecd')),
                ('reply_total', models.IntegerField(default=0, verbose_name='\u56de\u5e16\u6570')),
                ('reg_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6ce8\u518c\u65e5\u671f')),
                ('phone', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='\u624b\u673a')),
                ('weixin', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='\u5fae\u4fe1')),
                ('is_phone', models.BooleanField(default=False)),
                ('is_weixin', models.BooleanField(default=False)),
                ('is_name', models.BooleanField(default=False)),
                ('join_ip', models.CharField(default='', max_length=32, verbose_name='\u6ce8\u518c\u65f6ip')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u767b\u5f55IP')),
                ('is_carfax_manager', models.BooleanField(default=False, verbose_name='carfax\u7ba1\u7406\u6743\u9650')),
                ('source', models.CharField(choices=[('NORMAL', '\u666e\u901a\u7528\u6237'), ('WECHAT', '\u5fae\u4fe1\u7528\u6237')], default='NORMAL', max_length=16, verbose_name='\u6765\u6e90')),
                ('duoshuo_id', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('operating', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback_img', models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m')),
            ],
            options={
                'verbose_name': '\u8d26\u53f7\u95ee\u9898',
                'verbose_name_plural': '\u8d26\u53f7\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='ApplyForPickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='\u63a5\u673a\u59d3\u540d')),
                ('sex', models.CharField(default='', max_length=6, null=True, verbose_name='\u6027\u522b')),
                ('wx', models.CharField(default='', max_length=20, null=True, verbose_name='\u5fae\u4fe1\u53f7')),
                ('phone', models.CharField(default='', max_length=20, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('major', models.CharField(default='', max_length=20, null=True, verbose_name='\u5c31\u8bfb\u4e13\u4e1a')),
                ('email', models.EmailField(max_length=20, null=True, verbose_name='\u90ae\u7bb1')),
                ('baggage', models.CharField(default='', max_length=10, null=True, verbose_name='\u884c\u674e\u6570\u91cf')),
                ('flight', models.CharField(default='', max_length=20, null=True, verbose_name='\u822a\u73ed\u822a\u73ed\u53f7')),
                ('departure', models.CharField(default='', max_length=50, null=True, verbose_name='\u8d77\u98de\u65f6\u95f4')),
                ('departure_type', models.CharField(default='', max_length=50, null=True, verbose_name='\u8d77\u98de\u65f6\u95f4\u65f6\u533a')),
                ('landing_type', models.CharField(default='', max_length=50, null=True, verbose_name='\u843d\u5730\u65f6\u95f4\u65f6\u533a')),
                ('landing', models.CharField(default='', max_length=50, null=True, verbose_name='\u843d\u5730\u65f6\u95f4')),
                ('address', models.CharField(default='', max_length=100, verbose_name='\u5730\u5740')),
                ('contactor', models.CharField(default='', max_length=20, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('contacts_phone', models.CharField(default='', max_length=20, null=True, verbose_name='\u8054\u7cfb\u4eba\u8054\u7cfb\u65b9\u5f0f')),
                ('relation', models.CharField(default='', max_length=10, verbose_name='\u5173\u7cfb')),
                ('img1', models.ImageField(default='', upload_to='ad/', verbose_name='\u7167\u72471')),
                ('remark', models.CharField(default='', max_length=200, verbose_name='\u5907\u6ce8')),
                ('img2', models.ImageField(default='', upload_to='ad/', verbose_name='\u7167\u72472')),
                ('belong', models.CharField(choices=[('USC', 'USC'), ('UCLA', 'UCLA'), ('SMC', 'SMC'), ('UCSB', 'UCSB')], default='', max_length=50, verbose_name='\u6240\u5c5e\u5b66\u6821')),
            ],
            options={
                'verbose_name': '\u63a5\u673a\u7533\u8bf7\u8d44\u6599',
                'verbose_name_plural': '\u63a5\u673a\u7533\u8bf7\u8d44\u6599',
            },
        ),
        migrations.CreateModel(
            name='BuyCarNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
            ],
            options={
                'verbose_name': '\u4e70\u8f66\u901a\u77e5\u90ae\u4ef6',
                'verbose_name_plural': '\u4e70\u8f66\u901a\u77e5\u90ae\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Carfax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u5b57')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('wechat', models.CharField(max_length=64, verbose_name='\u5fae\u4fe1\u53f7')),
                ('is_reply', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u56de\u590d')),
                ('unreply_time', models.DateTimeField(blank=True, null=True, verbose_name='\u53d6\u6d88\u56de\u590d\u65f6\u95f4')),
                ('carfax_status', models.CharField(choices=[('ACTIVE', '\u6d3b\u8dc3'), ('BACKUP', '\u5df2\u5f52\u6863')], default='ACTIVE', max_length=16, verbose_name='\u72b6\u6001')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'verbose_name': 'carfax',
                'verbose_name_plural': 'carfax',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('message', models.TextField(default='', verbose_name='\u7559\u8a00\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7559\u8a00',
                'verbose_name_plural': '\u7528\u6237\u7559\u8a00',
            },
        ),
        migrations.CreateModel(
            name='CustomizedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(blank=True, default='other', max_length=10, null=True, verbose_name='\u8f66\u7c7b\u578b')),
                ('car_type_other', models.CharField(blank=True, max_length=10, null=True)),
                ('brand', models.TextField(blank=True, max_length=20, null=True)),
                ('vehicle_age', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('vehicle_miles', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('level_type', models.CharField(blank=True, default='other', max_length=10, null=True)),
                ('level_type_other', models.CharField(blank=True, max_length=10, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('\u81ea\u52a8', '\u81ea\u52a8'), ('\u624b\u52a8', '\u624b\u52a8')], default='auto', max_length=10, null=True)),
                ('drive_type', models.CharField(blank=True, choices=[('\u524d\u9a71', '\u524d\u9a71'), ('\u540e\u9a71', '\u540e\u9a71'), ('\u56db\u9a71', '\u56db\u9a71')], max_length=15, null=True)),
                ('color', models.TextField(blank=True, max_length=50, null=True)),
                ('oil_type', models.CharField(blank=True, choices=[('\u6c7d\u6cb9', '\u6c7d\u6cb9'), ('\u67f4\u6cb9', '\u67f4\u6cb9'), ('\u6cb9\u7535\u6df7\u5408', '\u6cb9\u7535\u6df7\u5408'), ('\u7535\u529b', '\u7535\u529b')], max_length=10, null=True)),
                ('turbo', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True)),
                ('contactor', models.TextField(default='admin', max_length=100)),
                ('phone', models.CharField(default='0', max_length=11, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('weixin', models.CharField(default='0', max_length=20, verbose_name='\u8054\u7cfb\u5fae\u4fe1')),
                ('claim', models.TextField(blank=True, max_length=400, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customized_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u6c7d\u8f66\u5b9a\u5236',
                'verbose_name_plural': '\u6c7d\u8f66\u5b9a\u5236',
            },
        ),
        migrations.CreateModel(
            name='DriveExamnation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(verbose_name='\u9898\u53f7')),
                ('content', models.CharField(max_length=500, verbose_name='\u5185\u5bb9')),
                ('bingo', models.CharField(max_length=200, verbose_name='\u7b54\u6848')),
                ('answer_a', models.CharField(default='', max_length=200, verbose_name='A')),
                ('answer_b', models.CharField(default='', max_length=200, verbose_name='B')),
                ('answer_c', models.CharField(default='', max_length=200, verbose_name='C')),
                ('img_content', models.URLField(default='', null=True, verbose_name='\u9009\u9879\u56fe\u7247')),
                ('img', models.URLField(default='', null=True, verbose_name='\u9898\u76ee\u7684\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u9a7e\u7167\u8003\u8bd5',
                'verbose_name_plural': '\u9a7e\u7167\u8003\u8bd5',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='\u9a8c\u8bc1\u7801')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('send_type', models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u5fd8\u8bb0\u5bc6\u7801'), ('off_posts', '\u5e16\u5b50\u5ba1\u6838')], max_length=10, verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u9001\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1\u7801',
                'verbose_name_plural': '\u90ae\u7bb1\u9a8c\u8bc1\u7801',
            },
        ),
        migrations.CreateModel(
            name='ExperFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '\u8054\u7cfb\u6211\u4eec',
                'verbose_name_plural': '\u8054\u7cfb\u6211\u4eec',
            },
        ),
        migrations.CreateModel(
            name='FuncFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=10)),
                ('time', models.DateField(blank=True, null=True, verbose_name='\u9047\u5230\u95ee\u9898\u65f6\u95f4')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback_img', models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m')),
            ],
            options={
                'verbose_name': '\u529f\u80fd\u5931\u7075',
                'verbose_name_plural': '\u529f\u80fd\u5931\u7075',
            },
        ),
        migrations.CreateModel(
            name='JsToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('lifetime', models.DateTimeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewStudentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570')),
                ('belong', models.CharField(choices=[('hd', '\u65b0\u751f\u6d3b\u52a8'), ('jj', '\u65b0\u751f\u63a5\u673a'), ('rx', '\u65b0\u751f\u5165\u5b66'), ('jz', '\u65b0\u751f\u9a7e\u7167')], default='jj', max_length=8, verbose_name='\u6240\u5c5e\u6a21\u5757')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u65b0\u751f\u8bc4\u8bba',
                'verbose_name_plural': '\u65b0\u751f\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='NewStudentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u9898\u76ee')),
                ('content', models.TextField(default='', max_length=20, verbose_name='\u5185\u5bb9')),
                ('content_detail', DjangoUeditor.models.UEditorField(default='', verbose_name='\u8be6\u7ec6\u5185\u5bb9')),
                ('img', models.ImageField(default='', upload_to='ad/', verbose_name='\u56fe\u7247')),
                ('url', models.URLField(default='', max_length=100, verbose_name='\u6587\u7ae0\u94fe\u63a5')),
                ('belong', models.CharField(choices=[('hd', '\u65b0\u751f\u6d3b\u52a8'), ('jj', '\u65b0\u751f\u63a5\u673a'), ('rx', '\u65b0\u751f\u5165\u5b66'), ('jz', '\u65b0\u751f\u9a7e\u7167')], default='jj', max_length=8, verbose_name='\u6240\u5c5e\u6a21\u5757')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u65b0\u751f\u6295\u7a3f',
                'verbose_name_plural': '\u65b0\u751f\u6295\u7a3f',
            },
        ),
        migrations.CreateModel(
            name='OtherFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('feedback_img', models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m')),
            ],
            options={
                'verbose_name': '\u5176\u4ed6\u95ee\u9898',
                'verbose_name_plural': '\u5176\u4ed6\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='SubmissionPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='house/', verbose_name='\u56fe\u7247')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csinla_accounts.NewStudentSubmission', verbose_name='\u6240\u5c5e\u6295\u7a3f')),
            ],
            options={
                'verbose_name': '\u6295\u7a3f\u56fe\u7247',
                'verbose_name_plural': '\u6295\u7a3f\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='Unread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('notice_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WechatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=199, verbose_name='\u5fae\u4fe1\u7684\u552f\u4e00\u8bc6\u522b\u7801')),
                ('unionid', models.CharField(blank=True, max_length=199, null=True, verbose_name='\u5fae\u4fe1\u5f00\u653e\u5e73\u53f0\u552f\u4e00\u8bc6\u522b\u7801')),
                ('scene_id', models.IntegerField(blank=True, null=True, verbose_name='\u5fae\u4fe1\u6c38\u4e45\u573a\u666fid')),
                ('nickname', models.CharField(blank=True, max_length=199, verbose_name='\u6635\u79f0')),
                ('headimgurl', models.CharField(blank=True, max_length=1000, verbose_name='\u5934\u50cf')),
                ('sex', models.IntegerField(choices=[(1, '\u7537'), (2, '\u5973'), (3, '\u672a\u77e5')], default=3, verbose_name='\u6027\u522b')),
                ('province', models.CharField(blank=True, max_length=199, verbose_name='\u7701\u4efd')),
                ('city', models.CharField(blank=True, max_length=199, verbose_name='\u57ce\u5e02')),
                ('country', models.CharField(blank=True, max_length=199, verbose_name='\u56fd\u5bb6')),
                ('userinfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5bf9\u5e94\u7684\u8d26\u53f7')),
            ],
            options={
                'verbose_name': '\u5fae\u4fe1\u4fe1\u606f',
                'verbose_name_plural': '\u5fae\u4fe1\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='WechatOpenToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=199, verbose_name='\u5fae\u4fe1\u7684\u552f\u4e00\u8bc6\u522b\u7801')),
                ('access_token', models.CharField(max_length=512, verbose_name='\u51ed\u636e\u5b57\u7b26')),
                ('refresh_token', models.CharField(max_length=512, verbose_name='\u5237\u65b0\u51ed\u636e')),
                ('expire_time', models.IntegerField(verbose_name='\u5230\u671f\u65f6\u95f4\u6233')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5bf9\u5e94\u8d26\u53f7')),
            ],
            options={
                'ordering': ['-expire_time'],
            },
        ),
        migrations.CreateModel(
            name='WxToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('lifetime', models.DateTimeField(default=0)),
            ],
        ),
    ]
