# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 13:44
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csinla_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(max_length=50, verbose_name='\u6240\u5c5e\u5b66\u6821')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('name', models.CharField(max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
            ],
            options={
                'verbose_name': '\u63a5\u673a\u5b66\u6821\u90ae\u4ef6',
                'verbose_name_plural': '\u63a5\u673a\u5b66\u6821\u90ae\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='ApplyUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='\u94fe\u63a5')),
                ('belong', models.CharField(choices=[('USC', 'USC'), ('UCLA', 'UCLA'), ('UCSB', 'UCSB'), ('UCI', 'UCI')], default='USC', max_length=20, verbose_name='\u6240\u5c5e\u5b66\u6821')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u63a5\u673a\u63d0\u9192URL',
                'verbose_name_plural': '\u63a5\u673a\u63d0\u9192URL',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('content', models.CharField(max_length=500, verbose_name='\u5185\u5bb9')),
                ('phone', models.CharField(max_length=20, verbose_name='\u624b\u673a\u53f7')),
                ('content_detail', models.CharField(max_length=1000, verbose_name='\u8be6\u7ec6\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u53cd\u9988',
                'verbose_name_plural': '\u9996\u9875\u53cd\u9988',
            },
        ),
        migrations.AddField(
            model_name='applyforpickup',
            name='zipcode',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='\u90ae\u7f16'),
        ),
        migrations.AlterField(
            model_name='applyforpickup',
            name='img2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='ad/', verbose_name='\u7167\u72472'),
        ),
        migrations.AlterField(
            model_name='newstudentsubmission',
            name='content',
            field=models.TextField(default='', max_length=150, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='newstudentsubmission',
            name='content_detail',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='\u8be6\u7ec6\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='newstudentsubmission',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='ad/', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='newstudentsubmission',
            name='title',
            field=models.CharField(max_length=50, verbose_name='\u9898\u76ee'),
        ),
        migrations.AlterField(
            model_name='newstudentsubmission',
            name='url',
            field=models.URLField(blank=True, default='', max_length=100, null=True, verbose_name='\u6587\u7ae0\u94fe\u63a5'),
        ),
    ]
