# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 11:53
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=256, verbose_name='\u6d3b\u52a8\u540d')),
                ('desc', models.TextField(default=b'', max_length=512, verbose_name='\u6d3b\u52a8\u63cf\u8ff0')),
                ('pre_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='\u5355\u4ef7(\u7f8e\u5143)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=b'fun/activity/cover_image/', verbose_name='\u5c01\u9762\u56fe')),
                ('ticket_image', models.ImageField(blank=True, null=True, upload_to=b'fun/activity/ticket_image/', verbose_name='\u95e8\u7968\u56fe')),
                ('level', models.IntegerField(default=100, verbose_name='\u663e\u793a\u4f18\u5148\u7ea7')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8',
                'verbose_name_plural': '\u6d3b\u52a8',
            },
        ),
        migrations.CreateModel(
            name='ActivityOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('customer_name', models.CharField(default=b'', max_length=64, verbose_name='\u5ba2\u6237\u59d3\u540d')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='\u5ba2\u6237\u90ae\u7bb1')),
                ('order_status', models.CharField(choices=[(b'NEED_PAY', '\u5f85\u4ed8\u6b3e'), (b'SENT', '\u5df2\u53d1\u653e'), (b'USED', '\u5df2\u4f7f\u7528'), (b'FAILED', '\u4ea4\u6613\u5931\u6548')], default=b'NEED_PAY', max_length=24, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('join_count', models.IntegerField(default=0, verbose_name='\u53c2\u4e0e\u5ba2\u4eba\u6570')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('order_no', models.CharField(default=b'', max_length=8, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='ActivityTimeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_time', models.DateTimeField(verbose_name='\u6d3b\u52a8\u65f6\u95f4')),
                ('max_count', models.IntegerField(verbose_name='\u6700\u5927\u53c2\u4e0e\u4eba\u6570')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fun.Activity', verbose_name='\u5bf9\u5e94\u6d3b\u52a8')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8\u65f6\u95f4\u70b9',
                'verbose_name_plural': '\u6d3b\u52a8\u65f6\u95f4\u70b9',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('message', models.TextField(default=b'', verbose_name='\u7559\u8a00\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7559\u8a00',
                'verbose_name_plural': '\u7528\u6237\u7559\u8a00',
            },
        ),
        migrations.CreateModel(
            name='Hoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u59d3\u540d')),
                ('gender', models.CharField(choices=[(b'MALE', '\u5148\u751f'), (b'FEMALE', '\u5973\u58eb'), (b'ORGANIZATION', '\u4fdd\u5bc6')], max_length=20, verbose_name='\u6027\u522b')),
                ('phone', models.CharField(max_length=32, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('photo', models.ImageField(upload_to=b'fun/hoster/photo/', verbose_name='\u7167\u7247')),
                ('email', models.EmailField(max_length=254, verbose_name='\u7535\u5b50\u90ae\u7bb1')),
                ('desc', models.TextField(default=b'', verbose_name='\u4e2a\u4eba\u4ecb\u7ecd')),
            ],
            options={
                'verbose_name': '\u5bfc\u6e38',
                'verbose_name_plural': '\u5bfc\u6e38',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('content_text', DjangoUeditor.models.UEditorField(blank=True, default=b'', null=True, verbose_name='\u8be6\u7ec6\u5185\u5bb9')),
                ('content_img', models.ImageField(blank=True, null=True, upload_to=b'fun/paragraph/content_img/', verbose_name='\u56fe\u7247\u4fe1\u606f')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fun.Activity', verbose_name='\u5bf9\u5e94\u6d3b\u52a8')),
            ],
            options={
                'ordering': ['create_time'],
                'verbose_name': '\u6d3b\u52a8\u8be6\u60c5\u6bb5\u843d',
                'verbose_name_plural': '\u6d3b\u52a8\u8be6\u60c5\u6bb5\u843d',
            },
        ),
        migrations.AddField(
            model_name='activityorder',
            name='activitytimeitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fun.ActivityTimeItem', verbose_name='\u5bf9\u5e94\u6d3b\u52a8\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='activity',
            name='hoster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fun.Hoster', verbose_name='\u5bfc\u6e38'),
        ),
    ]
