# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPViewResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(verbose_name='\u8bbf\u95ee\u65e5\u671f')),
                ('view_count', models.IntegerField(default=0, verbose_name='IP\u8bbf\u95ee\u6b21\u6570')),
                ('ip_count', models.IntegerField(default=0, verbose_name='\u8bbf\u95eeIP\u91cf')),
                ('view_type', models.CharField(default=b'', max_length=32, verbose_name='\u8bbf\u95ee\u7c7b\u578b')),
                ('user_view_count', models.IntegerField(default=0, verbose_name='\u7528\u6237\u8bbf\u95ee\u6b21\u6570')),
                ('user_count', models.IntegerField(default=0, verbose_name='\u7528\u6237\u8bbf\u95ee\u91cf')),
                ('collect_count', models.IntegerField(default=0, verbose_name='\u7528\u6237\u6536\u85cf\u91cf')),
                ('last_change_time', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
                ('join_list', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u8bbf\u95ee\u7528\u6237')),
            ],
            options={
                'ordering': ['-create_date', 'view_type'],
                'verbose_name': 'IP\u6d4f\u89c8\u8bb0\u5f55',
                'verbose_name_plural': 'IP\u6d4f\u89c8\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='TempTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_ticket', models.CharField(max_length=255, unique=True, verbose_name='temp_ticket')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('consumed', models.DateTimeField(null=True, verbose_name='consumed')),
                ('qrcode_img', models.ImageField(blank=True, null=True, upload_to=b'sso/tempticket/qrcode_img', verbose_name='\u4e8c\u7ef4\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=255, unique=True, verbose_name='ticket')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('consumed', models.DateTimeField(null=True, verbose_name='consumed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='ViewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('link', models.URLField(verbose_name='\u8bbf\u95ee\u5730\u5740')),
                ('ip', models.GenericIPAddressField(verbose_name='\u767b\u5f55IP')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='\u8bbf\u95ee\u65e5\u671f')),
                ('ip_view_type', models.CharField(default=b'', max_length=32, verbose_name='ip\u8bbf\u95ee\u7c7b\u578b')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.AddField(
            model_name='tempticket',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SSO.Ticket'),
        ),
    ]
